### ISSUE TITLE
add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [ncke/FortranFile#1]
I suggest adding topics such as `fortran`, `swift`, `io`, in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics and suggest editing the About section to say "Read data using Swift from files using a Fortran format specification."

I added your project to my list https://github.com/Beliavsky/Fortran-Tools#interoperability

**Comment by ncke** [comment]
Thanks for the suggestions and the listing.
